### ISSUE TITLE
Add firewall rules to resource in compile phase?

### ISSUE THREAD

**Issue by glenjamin** [chef-cookbooks/firewall#106]
Hello!

We've been bitten a few times lately by a failing chef run applying the `restart` action on the `firewall` resource - which modifies the list of rules to only include the `firewall_rule` resources that have run so far.

If something early in the run fails, but after the firewall resource init, then a bunch of rules get wiped out!

One thing that occurred to me was that because the `firewall_rule` providers don't actually do anything - they just append data to a hash and let `firewall` do the real work - then this could actually be done during the compile phase.

This way whenever the `firewall` resource updates, all of the expected rules will always be created.

This could be done via the `after_created` hook perhaps https://github.com/chef/chef/blob/master/lib/chef/resource.rb#L915 - maybe only if the `action` is set to `:compile` or something?

**Comment by martinb3** [comment]
It seems to be a similar issue to https://github.com/chef/chef/issues/2084. It seems like that reaches the same conclusion -- that collecting everything by the end of compile time is the best solution, and then using the template resource at converge to notify the restart.

In the case of this cookbook, my concern with collecting everything at compile time is that you could no longer use `action :nothing` on a `firewall_rule` resource and still trigger it with a notification later to make it get used.

Maybe this isn't a feature we really need though -- I'm having trouble coming up with examples of why you'd want a firewall rule to take effect due to a chef notification (e.g. due to another resource being updated). Most firewall rules should be present regardless of if another resource was brought into the correct state or not.

**Comment by martinb3** [comment]
I'm trying to think of examples where this change could remove functionality, e.g.:

```
package 'curl' do
  if platform_family?('debian')
    action :nothing
  else
    action :install
  end
  notifies :create, 'firewall_rule[allow curl outbound]', :immediately
end

firewall_rule 'allow curl outbound' do
  <some parameters that affect outbound curl packets>
  action :nothing
end
```

**Comment by glenjamin** [comment]
I've tried running this in-house via a fork, there seems to be an issue where the notify `:restart` isn't queued from the compile phase.

**Comment by martinb3** [comment]
I'm still really torn on this one. I'm wondering if it would almost be better to solve through documentation -- converge vs. compile time (in my opinion) isn't really a Chef 'internal' so much as a fact of life that everyone using it eventually must wrestle with. I'm wondering if we shouldn't just start an FAQ, and explain how to do `.run_action` on resources if you want them to run at compile time.
